services:
  frontend:
    build: ./
    command: npm start -- --host 0.0.0.0
    volumes: 
      - ../Chalk-Frontend:/src
    ports:
      - 5173:5173
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
