openapi: "3.0.3"
info:
  title: Chalk - Test Your Knowledge
  version: "1.0.0"
servers:
  - url: https://localhost:8080/v1/

paths:
  /user:
    post:
      summary: Create user
      description: This method is used to create an user regardless of its type.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user
              properties:
                user:
                  oneOf:
                    - $ref: '#/components/schemas/Student'
                    - $ref: '#/components/schemas/Specialist'
                    - $ref: '#/components/schemas/InstitutionManager'
      responses:
        "200":
          description: OK

    get:
      parameters:
        - name: institution
          in: query
          schema:
            type: string
          description: >
            Find users from this institution.
        - name: course
          in: query
          schema:
            type: string
          description: >
              Find users from this course (institution is required).
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                    - $ref: '#/components/schemas/Student'
                    - $ref: '#/components/schemas/Specialist'
                    - $ref: '#/components/schemas/InstitutionManager'
        '400':
          description: Either 'institution' or 'course'+'institution' are required.


  /user/{userId}:
    parameters:
      - name: userId
        in: path
        description: User identifier
        required: true
        schema:
          type: string
          example: "user1"
    get:
      summary: Get user by user id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Student'
                  - $ref: '#/components/schemas/Specialist'
                  - $ref: '#/components/schemas/InstitutionManager'
        '400':
          description: Invalid user id supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update user
      description: Update an existent user in the store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                exercise:
                  oneOf:
                    - $ref: '#/components/schemas/Student'
                    - $ref: '#/components/schemas/Specialist'
                    - $ref: '#/components/schemas/InstitutionManager'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid user id supplied
        '404':
          description: User not found

    delete:
      tags:
        - user
      summary: Delete user
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid username supplied
        '404':
          description: User not found

components:
  schemas:
    User:
      description: "Basic properties of an user."
      type: object
      required:
        - name
      properties:
        id:
          type: string
        name:
          type: string
        photoPath:
          type: string
          
    SpecialistWithoutId:
      description: "Specialist's Schema. The user id is not required."
      allOf:
        - $ref: "#/components/schemas/User"
      example:
        name: "Alexandre Martins"
        photoPath: "https://i.imgur.com/FRwhrhG.jpg"
        
        
    Specialist:
      description: "Specialist's Schema"
      required:
        - id
      allOf:
        - $ref: '#/components/schemas/SpecialistWithoutId'
      example:
        id: "id_Alex"
        name: "Alexandre Martins"
        photoPath: "https://i.imgur.com/FRwhrhG.jpg"
          
    StudentWithoutId:
      description: "Student's Schema. The user id is not required."
      allOf:
        - $ref: "#/components/schemas/User"
      example:
        name: "Luís Silva"
        photoPath: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Osama_bin_Laden%2C_portr%C3%A6t.jpg"

    Student:
      description: "Student's Schema"
      required:
        - id
      allOf:
        - $ref: '#/components/schemas/StudentWithoutId'
      example:
        id: "id_Luis"
        name: "Luĩs Silva"
        photoPath: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Osama_bin_Laden%2C_portr%C3%A6t.jpg"
          
    InstitutionManagerWithoutId:
      description: "Institution Manager's Schema. The user id is not required."
      required:
        - institutionId
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            institutionId:
              type: string
      example:
        name: "Rui Braga"
        photoPath: "https://media.vogue.fr/photos/5c3618b2093f3f72befae9d6/2:3/w_2560%2Cc_limit/mood_gosling_8365.jpeg?lang=eng"
        institutionId: "institution1"
          
    InstitutionManager:
      description: "Institution Manager's Schema"
      required:
        - id
      allOf:
        - $ref: '#/components/schemas/InstitutionManagerWithoutId'
      example:
        id: "id_Ray"
        name: "Rui Braga"
        photoPath: "https://media.vogue.fr/photos/5c3618b2093f3f72befae9d6/2:3/w_2560%2Cc_limit/mood_gosling_8365.jpeg?lang=eng"
        institutionId: "institution1"