openapi: 3.0.3
info:
  title: Chalk - Test Your Knowledge
  version: 1.0.0
servers:
  - url: https://localhost:8080/v1/
components:
  schemas:
    $ref: components/schemas/_index.yml
paths:
  # users
  /users:
    $ref: paths/users.yml
  /users/managers:
    $ref: paths/users/managers.yml
  /users/specialists:
    $ref: paths/users/specialists.yml
  /users/students:
    $ref: paths/users/students.yml
  /users/{userId}:
    $ref: paths/users/{userId}.yml

  # institutions
  /institutions:
    $ref: paths/institutions.yml
  /institutions/{institutionId}:
    $ref: paths/institutions/{institutionId}.yml

  # courses
  /courses:
    $ref: paths/courses.yml
  /courses/{courseId}:
    $ref: paths/courses/{courseId}.yml

  # exercises
  /exercises:
    $ref: paths/exercises.yml
  /exercises/resolutions/{resolutionId}:
    $ref: paths/exercises/resolutions/{resolutionId}.yml
  /exercises/resolutions/{resolutionId}/comment:
    $ref: paths/exercises/resolutions/{resolutionId}/comment.yml
  /exercises/resolutions/{resolutionId}/manual-correction:
    $ref: paths/exercises/resolutions/{resolutionId}/manual-correction.yml
  /exercises/rubrics/{rubricId}:
    $ref: paths/exercises/rubrics/{rubricId}.yml
  /exercises/tag:
    $ref: paths/exercises/tag.yml
  /exercises/{exerciseId}:
    $ref: paths/exercises/{exerciseId}.yml
  /exercises/{exerciseId}/duplicate:
    $ref: paths/exercises/{exerciseId}/duplicate.yml
  /exercises/{exerciseId}/resolutions:
    $ref: paths/exercises/{exerciseId}/resolutions.yml
  /exercises/{exerciseId}/resolutions/correction:
    $ref: paths/exercises/{exerciseId}/resolutions/correction.yml
  /exercises/{exerciseId}/resolutions/count:
    $ref: paths/exercises/{exerciseId}/resolutions/count.yml
  /exercises/{exerciseId}/resolutions/{studentId}/count:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/count.yml
  /exercises/{exerciseId}/resolutions/{studentId}/ids:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/ids.yml
  /exercises/{exerciseId}/resolutions/{studentId}/last:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/last.yml
  /exercises/{exerciseId}/rubric:
    $ref: paths/exercises/{exerciseId}/rubric.yml
  
  # tests

  /tests:
    $ref: paths/tests.yml
  /tests/resolutions/{resolutionId}:
    $ref: paths/tests/resolutions/{resolutionId}.yml
  /tests/{testId}:
    $ref: paths/tests/{testId}.yml
  /tests/{testId}/duplicate:
    $ref: paths/tests/{testId}/duplicate.yml
  /tests/{testId}/resolutions:
    $ref: paths/tests/{testId}/resolutions.yml
  /tests/{testId}/resolutions/correction:
    $ref: paths/tests/{testId}/resolutions/correction.yml
  /tests/{testId}/resolutions/count:
    $ref: paths/tests/{testId}/resolutions/count.yml
  /tests/{testId}/resolutions/{studentId}/can-submit:
    $ref: paths/tests/{testId}/resolutions/{studentId}/can-submit.yml
  /tests/{testId}/resolutions/{studentId}/count:
    $ref: paths/tests/{testId}/resolutions/{studentId}/count.yml
  /tests/{testId}/resolutions/{studentId}/ids:
    $ref: paths/tests/{testId}/resolutions/{studentId}/ids.yml
  /tests/{testId}/resolutions/{studentId}/last:
    $ref: paths/tests/{testId}/resolutions/{studentId}/last.yml

  # subscriptions plans and subscription
  /subscriptions:
    $ref: paths/subscriptions.yml
  /subscriptions/institutions:
    $ref: paths/subscriptions/institutions.yml
  /subscriptions/institutions/{institutionId}:
    $ref: paths/subscriptions/institutions/{institutionId}.yml
  /subscriptions/specialists:
    $ref: paths/subscriptions/specialists.yml
  /subscriptions/specialists/{specialistId}:
    $ref: paths/subscriptions/specialists/{specialistId}.yml
  /subscriptions/students:
    $ref: paths/subscriptions/students.yml
  /subscriptions/students/{studentId}:
    $ref: paths/subscriptions/students/{studentId}.yml
  /subscriptions/{subscriptionPlanId}:
    $ref: paths/subscriptions/{subscriptionPlanId}.yml