openapi: 3.0.3
info:
  title: Chalk - Test Your Knowledge
  version: 1.0.0
servers:
  - url: https://localhost:8080/v1/
components:
  schemas:
    $ref: components/schemas/_index.yml
paths:
  # users
  /user:
    $ref: paths/user.yml
  /user/manager:
    $ref: paths/user/manager.yml
  /user/specialist:
    $ref: paths/user/specialist.yml
  /user/student:
    $ref: paths/user/student.yml
  /user/{userId}:
    $ref: paths/user/{userId}.yml

  # institutions
  /institution:
    $ref: paths/institution.yml
  /institution/{institutionId}:
    $ref: paths/institution/{institutionId}.yml

  # courses
  /course:
    $ref: paths/course.yml
  /course/{courseId}:
    $ref: paths/course/{courseId}.yml

  # exercises
  /exercises:
    $ref: paths/exercises.yml
  /exercises/resolutions/{resolutionId}:
    $ref: paths/exercises/resolutions/{resolutionId}.yml
  /exercises/resolutions/{resolutionId}/comment:
    $ref: paths/exercises/resolutions/{resolutionId}/comment.yml
  /exercises/resolutions/{resolutionId}/manual-correction:
    $ref: paths/exercises/resolutions/{resolutionId}/manual-correction.yml
  /exercises/rubrics/{rubricId}:
    $ref: paths/exercises/rubrics/{rubricId}.yml
  /exercises/tag:
    $ref: paths/exercises/tag.yml
  /exercises/{exerciseId}:
    $ref: paths/exercises/{exerciseId}.yml
  /exercises/{exerciseId}/duplicate:
    $ref: paths/exercises/{exerciseId}/duplicate.yml
  /exercises/{exerciseId}/resolutions:
    $ref: paths/exercises/{exerciseId}/resolutions.yml
  /exercises/{exerciseId}/resolutions/correction:
    $ref: paths/exercises/{exerciseId}/resolutions/correction.yml
  /exercises/{exerciseId}/resolutions/count:
    $ref: paths/exercises/{exerciseId}/resolutions/count.yml
  /exercises/{exerciseId}/resolutions/{studentId}/count:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/count.yml
  /exercises/{exerciseId}/resolutions/{studentId}/ids:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/ids.yml
  /exercises/{exerciseId}/resolutions/{studentId}/last:
    $ref: paths/exercises/{exerciseId}/resolutions/{studentId}/last.yml
  /exercises/{exerciseId}/rubric:
    $ref: paths/exercises/{exerciseId}/rubric.yml
  
  # tests

  /tests:
    $ref: paths/tests.yml
  /tests/resolutions/{resolutionId}:
    $ref: paths/tests/resolutions/{resolutionId}.yml
  /tests/{testId}:
    $ref: paths/tests/{testId}.yml
  /tests/{testId}/duplicate:
    $ref: paths/tests/{testId}/duplicate.yml
  /tests/{testId}/resolutions:
    $ref: paths/tests/{testId}/resolutions.yml
  /tests/{testId}/resolutions/correction:
    $ref: paths/tests/{testId}/resolutions/correction.yml
  /tests/{testId}/resolutions/count:
    $ref: paths/tests/{testId}/resolutions/count.yml
  /tests/{testId}/resolutions/{studentId}/can-submit:
    $ref: paths/tests/{testId}/resolutions/{studentId}/can-submit.yml
  /tests/{testId}/resolutions/{studentId}/count:
    $ref: paths/tests/{testId}/resolutions/{studentId}/count.yml
  /tests/{testId}/resolutions/{studentId}/ids:
    $ref: paths/tests/{testId}/resolutions/{studentId}/ids.yml
  /tests/{testId}/resolutions/{studentId}/last:
    $ref: paths/tests/{testId}/resolutions/{studentId}/last.yml

  # subscriptions plans and subscription
  /subscription:
    $ref: paths/subscription.yml
  /subscription/institution:
    $ref: paths/subscription/institution.yml
  /subscription/institution/{institutionId}:
    $ref: paths/subscription/institution/{institutionId}.yml
  /subscription/specialist:
    $ref: paths/subscription/specialist.yml
  /subscription/specialist/{specialistId}:
    $ref: paths/subscription/specialist/{specialistId}.yml
  /subscription/student:
    $ref: paths/subscription/student.yml
  /subscription/student/{studentId}:
    $ref: paths/subscription/student/{studentId}.yml
  /subscription/{subscriptionPlanId}:
    $ref: paths/subscription/{subscriptionPlanId}.yml