# docker permissions
# https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket
services:
  mongodb:
    image: 'mongo:7.0.3'
    environment:
      - 'MONGO_INITDB_DATABASE=chalktyk'
      - 'MONGO_INITDB_ROOT_PASSWORD=password'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    volumes:
      - mongo_db:/data/db
  postgres:
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=chalktyk'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/data/db

volumes:
  postgres_db:
    driver:
      local
  mongo_db:
    driver:
      local